
@baseUrl=http://yapi.demo.qunar.com/mock/34134/app
###
GET {{baseUrl}}/products HTTP/1.1

###
POST {{baseUrl}}/posts HTTP/1.1
Content-Type: : application/json

{
    "id": 1,
    "userId": 1,
    "title": "Hello World!"

}

### 
PUT {{baseUrl}}/products/201
Content-Type: : application/json

{
    "id": 1,
    "userId": 1,
    "title": "Hello World!"

}